### ISSUE TITLE
Fault Tolerance and Runtime Assumptions

### ISSUE THREAD

**Issue by rmascarenhas** [UBC-NSS/pgo#117] opened 2019-04-24 19:10 UTC
If a node in a system compiled by PGo crashes, attempting to send a message to that node will cause an underlying error to be bubbled up to the user's main. Since all bets are off in this case (including partial state applications), ideally the runtime should provide better abstractions that allow user-defined behavior on failures (i.e., maybe a different archetype implementation that exposes failures somehow).

**Comment by bestchai** [comment] 2019-04-24 19:16
> maybe a different archetype implementation that exposes failures somehow

I like this idea -- in some cases the spec writer doesn't care about failures because they assume fate sharing and want the whole thing to crash and burn. In other cases, they want to explicitly know about failures and have a notification channel for these so that other archetypes can respond to failures.

**Comment by shayanh** [comment] 2021-09-02 21:59
Duplicate of #134. Now we carefully considered assumptions of the runtime about the environment and archetypes.

**Closed by shayanh** 2021-09-02 21:59 UTC
